package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.GestorePiattaforma;
import control.SessionManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Locale;

public class AreaRiservataDocente {
    private JPanel contentPane;
    private JScrollPane contentMateriali;
    private JTable tblMateriali;
    private JPanel contentInformazioniDocente;
    private JLabel lblCorsi;
    private JLabel lbl_informazioniDocente;
    private JPanel descrizioneDashboard;
    private JLabel iconaLogo;
    private JButton btnLogout;

    private JFrame myFrame;
    private JFrame frameLogin;

    //componenti per le operazioni sui materiali didattici
    private DefaultTableModel tableModel;
    private JPopupMenu contextMenu;
    private JMenuItem menuApri;

    private String emailUtente;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, -1));
        descrizioneDashboard = new JPanel();
        descrizioneDashboard.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(descrizioneDashboard, new GridConstraints(0, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        iconaLogo = new JLabel();
        iconaLogo.setText("");
        descrizioneDashboard.add(iconaLogo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnLogout = new JButton();
        Font btnLogoutFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnLogout.getFont());
        if (btnLogoutFont != null) btnLogout.setFont(btnLogoutFont);
        btnLogout.setMargin(new Insets(10, 10, 10, 10));
        btnLogout.setText("Logout");
        descrizioneDashboard.add(btnLogout, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        descrizioneDashboard.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        contentMateriali = new JScrollPane();
        contentPane.add(contentMateriali, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblMateriali = new JTable();
        tblMateriali.setMaximumSize(new Dimension(2147483647, 50));
        tblMateriali.setPreferredSize(new Dimension(150, 50));
        tblMateriali.setRowHeight(25);
        contentMateriali.setViewportView(tblMateriali);
        contentInformazioniDocente = new JPanel();
        contentInformazioniDocente.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentInformazioniDocente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblCorsi = new JLabel();
        Font lblCorsiFont = this.$$$getFont$$$(null, Font.BOLD, 16, lblCorsi.getFont());
        if (lblCorsiFont != null) lblCorsi.setFont(lblCorsiFont);
        lblCorsi.setText("Area Riservata del Docente");
        contentInformazioniDocente.add(lblCorsi, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbl_informazioniDocente = new JLabel();
        Font lbl_informazioniDocenteFont = this.$$$getFont$$$(null, Font.BOLD, 16, lbl_informazioniDocente.getFont());
        if (lbl_informazioniDocenteFont != null) lbl_informazioniDocente.setFont(lbl_informazioniDocenteFont);
        lbl_informazioniDocente.setText("Label");
        contentInformazioniDocente.add(lbl_informazioniDocente, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    public AreaRiservataDocente(String emailUtente) {
        this.emailUtente = emailUtente;
        inizializzaTabella();
        inizializzaMenu();
        setAzioni();
        aggiornaTabellaMateriali();
        lbl_informazioniDocente.setText(emailUtente);

        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/logoPiattaforma.png"));
        Image img = logoIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        iconaLogo.setIcon(new ImageIcon(img));
        iconaLogo.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        iconaLogo.setHorizontalAlignment(SwingConstants.CENTER);

    }

    private void inizializzaMenu() {
        contextMenu = new JPopupMenu();
        menuApri = new JMenuItem("Apri Materiale");

        contextMenu.add(menuApri);

        //collegamento per far apparire il menu
        tblMateriali.addMouseListener(new MouseAdapter() {

            // tasto destro
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger())
                    mouseClicked(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger())
                    mouseClicked(e);
            }

            // click sinistro sulla colonna ⋮
            @Override
            public void mouseClicked(MouseEvent e) {
                int col = tblMateriali.columnAtPoint(e.getPoint());
                int row = tblMateriali.rowAtPoint(e.getPoint());
                if (col == 4 && row >= 0 && row < tblMateriali.getRowCount()) {
                    String valorePrimaColonna = (String) tblMateriali.getValueAt(row, 0);
                    if ("Non ci sono corsi".equals(valorePrimaColonna)) {
                        // Se c'è scritto "Non ci sono corsi", ignoriamo il click.
                        return;
                    }
                    tblMateriali.setRowSelectionInterval(row, row);
                    contextMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }

        });
    }

    public JFrame apriAreaRiservataDocente() {
        // 1. Impostazioni base della finestra
        JFrame frame = new JFrame("Studio Paradigm - Area Riservata Docente");
        this.myFrame = frame;
        frame.setContentPane(contentPane); // Collega il pannello principale


        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        return frame;
    }

    private void setAzioni() {
        //Azione click Apri
        menuApri.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int rigaSelezionata = tblMateriali.getSelectedRow();

                // Prima controlliamo che una riga sia effettivamente selezionata!
                if (rigaSelezionata != -1) {
                    String titoloSelezionato = tblMateriali.getValueAt(rigaSelezionata, 1).toString();
                    if (myFrame != null) {
                        myFrame.dispose();

                        DocenteDashboardMateriali form = new DocenteDashboardMateriali(emailUtente, String.valueOf(tblMateriali.getValueAt(rigaSelezionata, 1)));

                        form.apriDocenteDashboard();
                    }


                }
            }
        });
        //bottone logout FATTO
        btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Logout effettuato con successo! Arrivederci.",
                        "Ritorno al login",
                        JOptionPane.INFORMATION_MESSAGE
                );

                if (myFrame != null) {
                    myFrame.dispose();
                    SessionManager.getInstance().logout();
                    LoginForm form = new LoginForm();
                    frameLogin = form.apriLoginForm();
                    frameLogin.setLocationRelativeTo(null);
                    frameLogin.setVisible(true);
                }
            }
        });

    }

    private void inizializzaTabella() {
        // Definisci i nomi delle colonne
        String[] nomiColonne = {"Codice", "Titolo", "Descrizione", "Anno Accademico", "Materiale"};

        // Crea il modello personalizzato bloccando la modifica delle celle
        tableModel = new DefaultTableModel(nomiColonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Imposta il modello della tabella come modello della visualizzazione
        tblMateriali.setModel(tableModel);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblMateriali.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tblMateriali.getColumnModel().getColumn(4).setPreferredWidth(50);
    }

    //metodo per popolare la tabella
    public void aggiornaTabellaMateriali() {
        // Richiama il tuo metodo per ottenere i dati
        List<String[]> datiCorsi = GestorePiattaforma.visualizzaElencoCorsi(emailUtente);

        //Ottieni il modello della tua JTable
        tableModel = (DefaultTableModel) tblMateriali.getModel();

        // Pulire la tabella dai dati vecchi
        tableModel.setRowCount(0);

        //Cicla la lista e aggiunge ogni array come riga al modello
        for (String[] riga : datiCorsi) {
            tableModel.addRow(riga);
        }
    }

}
