package boundary;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.GestorePiattaformaChiara;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.Locale;
import java.util.List;

//aggiungere i 3 puntini nell ultima colonna al centro


public class DocenteDashboardMateriali {
    // componenti principali
    private JPanel contentPane;
    private JPanel contentRicerca;
    private JTextField txtRicerca;
    private JComboBox cmbFiltro;
    private JButton btnRicerca;
    private JTable tblMateriali;
    private JScrollPane contentMateriali;
    private JPanel contentAggiungi;
    private JButton btnAggiungi;
    private JLabel lblMateriali;
    private JLabel lblCorso;
    private JPanel descrizioneDashboard;
    private JLabel iconaLogo;
    private JLabel lblDocente;
    private JLabel lbl_informazioniDocenti;
    private JButton btnLogout;

    //componenti per le operazioni sui materiali didattici
    private DefaultTableModel tableModel;
    private JPopupMenu contextMenu;
    private JMenuItem menuApri;
    private JMenuItem menuModifica;
    private JMenuItem menuRimuovi;

    //frame per la registrazione dei materiali didattici
    private JFrame frameAggiungi;
    private JFrame myFrame;
    private JFrame frameLogin;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, 15));
        contentRicerca = new JPanel();
        contentRicerca.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), 10, -1));
        contentPane.add(contentRicerca, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        cmbFiltro = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("titolo");
        defaultComboBoxModel1.addElement("descrizione");
        defaultComboBoxModel1.addElement("categoria");
        cmbFiltro.setModel(defaultComboBoxModel1);
        contentRicerca.add(cmbFiltro, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRicerca = new JButton();
        Font btnRicercaFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnRicerca.getFont());
        if (btnRicercaFont != null) btnRicerca.setFont(btnRicercaFont);
        btnRicerca.setText("Ricerca");
        contentRicerca.add(btnRicerca, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtRicerca = new JTextField();
        txtRicerca.setText("Inserisci parola chiave ...");
        contentRicerca.add(txtRicerca, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        contentMateriali = new JScrollPane();
        contentPane.add(contentMateriali, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblMateriali = new JTable();
        tblMateriali.setRowHeight(25);
        contentMateriali.setViewportView(tblMateriali);
        contentAggiungi = new JPanel();
        contentAggiungi.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentAggiungi, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnAggiungi = new JButton();
        Font btnAggiungiFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnAggiungi.getFont());
        if (btnAggiungiFont != null) btnAggiungi.setFont(btnAggiungiFont);
        btnAggiungi.setText("+ Aggiungi Materiale");
        contentAggiungi.add(btnAggiungi, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblMateriali = new JLabel();
        Font lblMaterialiFont = this.$$$getFont$$$(null, Font.BOLD, 16, lblMateriali.getFont());
        if (lblMaterialiFont != null) lblMateriali.setFont(lblMaterialiFont);
        lblMateriali.setText("Materiali Didattici Corso");
        contentAggiungi.add(lblMateriali, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCorso = new JLabel();
        Font lblCorsoFont = this.$$$getFont$$$(null, Font.BOLD, 16, lblCorso.getFont());
        if (lblCorsoFont != null) lblCorso.setFont(lblCorsoFont);
        lblCorso.setText("\"nome_corso\"");
        contentAggiungi.add(lblCorso, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentAggiungi.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        descrizioneDashboard = new JPanel();
        descrizioneDashboard.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(descrizioneDashboard, new GridConstraints(0, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        iconaLogo = new JLabel();
        iconaLogo.setText("");
        descrizioneDashboard.add(iconaLogo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDocente = new JLabel();
        lblDocente.setText("Docente");
        descrizioneDashboard.add(lblDocente, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbl_informazioniDocenti = new JLabel();
        lbl_informazioniDocenti.setText("\"nome docente\"");
        descrizioneDashboard.add(lbl_informazioniDocenti, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        descrizioneDashboard.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btnLogout = new JButton();
        Font btnLogoutFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnLogout.getFont());
        if (btnLogoutFont != null) btnLogout.setFont(btnLogoutFont);
        btnLogout.setMargin(new Insets(10, 10, 10, 10));
        btnLogout.setText("Logout");
        descrizioneDashboard.add(btnLogout, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        contentPane.add(spacer4, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


    //Aggiungere nel costruttore l'email dell'utente e il corso
    public DocenteDashboardMateriali(String emailUtente, String nomeCorso){
        inizializzaTabella();
        inizializzaMenu();
        setAzioni(emailUtente, nomeCorso);
        aggiornaTabellaMateriali(emailUtente, nomeCorso);

        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/logoPiattaforma.png"));
        Image img = logoIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        iconaLogo.setIcon(new ImageIcon(img));
        iconaLogo.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        iconaLogo.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void apriDocenteDashboard() {
        // 1. Impostazioni base della finestra
        JFrame frame = new JFrame("Studio Paradigm - Dashboard Docente");
        this.myFrame = frame;
        frame.setContentPane(contentPane); // Collega il pannello principale
        txtRicerca.setForeground(Color.GRAY);


        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


    }

    private void inizializzaMenu() {
        contextMenu = new JPopupMenu();
        menuApri = new JMenuItem("Apri File");
        menuModifica = new JMenuItem("Modifica Materiale");
        menuRimuovi = new JMenuItem("Rimuovi Materiale");

        contextMenu.add(menuApri);
        contextMenu.add(menuModifica);
        contextMenu.add(menuRimuovi);

        //collegamento per far apparire il menu
        tblMateriali.addMouseListener(new MouseAdapter() {

            // tasto destro
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger())
                    mouseClicked(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger())
                    mouseClicked(e);
            }

            // click sinistro sulla colonna ⋮
            @Override
            public void mouseClicked(MouseEvent e) {
                int col = tblMateriali.columnAtPoint(e.getPoint());
                int row = tblMateriali.rowAtPoint(e.getPoint());
                if (col == 6 && row >= 0 &&row < tblMateriali.getRowCount()) {
                    tblMateriali.setRowSelectionInterval(row, row);
                    contextMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }

        });
    }

    private void inizializzaTabella() {
        // Definisci i nomi delle colonne
        String[] nomiColonne = {"Titolo", "Categoria", "Descrizione","Data Pubblicazione", "Sezione", "Stato", "Azioni"};

        // Crea il modello personalizzato bloccando la modifica delle celle
        tableModel = new DefaultTableModel(nomiColonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Imposta il modello della tabella come modello della visualizzazione
        tblMateriali.setModel(tableModel);

        // Centra il contenuto dell'ultima colonna (indice 5)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblMateriali.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        tblMateriali.getColumnModel().getColumn(6).setPreferredWidth(50);
    }

    //metodo per popolare la tabella
    public void aggiornaTabellaMateriali(String emailUtente, String nomeCorso) {
        // Richiama il tuo metodo per ottenere i dati
        List<String[]> datiMateriali = GestorePiattaformaChiara.VisualizzaMateriali(emailUtente, nomeCorso);

        //Ottieni il modello della tua JTable
        tableModel = (DefaultTableModel) tblMateriali.getModel();

        // Pulire la tabella dai dati vecchi
        tableModel.setRowCount(0);

        //Cicla la lista e aggiunge ogni array come riga al modello
        for (String[] riga : datiMateriali) {
            tableModel.addRow(riga);
        }
    }

    private void setAzioni(String emailUtente, String nomeCorso) {
        //Azione click Aggiungi FATTA
        btnAggiungi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameAggiungi == null || !frameAggiungi.isDisplayable()) {
                    DocenteAggiungiModificaMateriali form = new DocenteAggiungiModificaMateriali();
                    frameAggiungi = form.apriDocenteAggiungiModificaMateriali();
                    frameAggiungi.setLocationRelativeTo(null);
                    frameAggiungi.setVisible(true);
                } else {
                    frameAggiungi.toFront();
                    frameAggiungi.requestFocus();
                }
            }
        });


        //Azione click Modifica FATTA
        menuModifica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                int rigaSelezionata = tblMateriali.getSelectedRow();
                //recupero dati e passaggio al form
                if (frameAggiungi == null || !frameAggiungi.isDisplayable()) {

                    String titoloSelezionato = tblMateriali.getValueAt(rigaSelezionata, 0).toString();
                    String categoriaSelezionata = tblMateriali.getValueAt(rigaSelezionata, 1).toString();
                    String descrizioneSelezionata = tblMateriali.getValueAt(rigaSelezionata, 2).toString();
                    String sezioneSelezionata = tblMateriali.getValueAt(rigaSelezionata, 4).toString();
                    String statoSelezionato = tblMateriali.getValueAt(rigaSelezionata, 5).toString();


                    DocenteAggiungiModificaMateriali form = new DocenteAggiungiModificaMateriali(
                            titoloSelezionato,
                            descrizioneSelezionata,
                            categoriaSelezionata,
                            sezioneSelezionata,
                            statoSelezionato
                    );

                    frameAggiungi = form.apriDocenteAggiungiModificaMateriali();
                    frameAggiungi.setLocationRelativeTo(null);
                    frameAggiungi.setVisible(true);
                } else {
                    frameAggiungi.toFront();
                    frameAggiungi.requestFocus();
                }
            }
        });

        //Azione click Rimuovi
        menuRimuovi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                int rigaSelezionata = tblMateriali.getSelectedRow();
                String titoloSelezionato = tblMateriali.getValueAt(rigaSelezionata, 0).toString();

                //Richiesta Scelta
                int scelta = JOptionPane.showConfirmDialog(
                        myFrame,
                        "Sei sicuro di voler eliminare definitivamente il materiale:\n\"" + titoloSelezionato + "\"?",
                        "Conferma Eliminazione",
                        JOptionPane.YES_NO_OPTION, // Mostra i pulsanti "Sì" e "No"
                        JOptionPane.QUESTION_MESSAGE // Mostra l'icona del punto interrogativo
                );

                if (scelta == JOptionPane.YES_OPTION){
                    GestorePiattaformaChiara.eliminaMateriale(emailUtente, nomeCorso, titoloSelezionato);
                    aggiornaTabellaMateriali(emailUtente, nomeCorso);
                    JOptionPane.showMessageDialog(myFrame, "Materiale eliminato con successo.", "Operazione completata", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(myFrame, "Operazione annullata.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                }
            }
        });

        //Azione click Apri (aggiungere il percorso del file)
        //va delegato al controller
        menuApri.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int rigaSelezionata = tblMateriali.getSelectedRow();

                if (rigaSelezionata != -1) {
                    // Recupera il percorso del file
                    //TBD

                    try {
                        java.io.File file = new java.io.File("TBD AGGIUNGERE PERCORSO");
                        if (file.exists() && java.awt.Desktop.isDesktopSupported()) {
                            java.awt.Desktop.getDesktop().open(file);
                        } else {
                            JOptionPane.showMessageDialog(contentPane, "Impossibile aprire il file o file non trovato.", "Errore", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(contentPane,
                                "Errore nell'apertura del file: " + ex.getMessage(),
                                "Errore", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        });

        //Azione click test ricerca FATTA
        txtRicerca.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtRicerca.getText().equals("Inserisci parola chiave ...")) {
                    txtRicerca.setText("");
                    txtRicerca.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtRicerca.getText().isBlank()) {
                    txtRicerca.setText("Inserisci parola chiave ...");
                    txtRicerca.setForeground(Color.GRAY);
                }
            }
        });

        //Azione click ricerca
        btnRicerca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){

            }
        });

        //bottone logout FATTO
        btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                JOptionPane.showMessageDialog(
                        null,
                        "Logout effettuato con successo! Arrivederci.",
                        "Ritorno al login",
                        JOptionPane.INFORMATION_MESSAGE
                );

                if (myFrame != null) {
                    myFrame.dispose();
                    LoginForm form = new LoginForm();
                    frameLogin = form.apriLoginForm();
                    frameLogin.setLocationRelativeTo(null);
                    frameLogin.setVisible(true);
                }
            }
        });

    }

    //prova per visualizzare
    public static void main(String[] args) {
        DocenteDashboardMateriali dashboard = new DocenteDashboardMateriali("domenico.amalfitano@unina.it", "Ingegneria del Software");
        dashboard.apriDocenteDashboard();
    }


}
