package boundary;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;


public class DocenteDashboardMateriali {
    // componenti principali
    private JPanel contentPane;
    private JPanel contentRicerca;
    private JTextField txtRicerca;
    private JComboBox cmbFiltro;
    private JButton btnRicerca;
    private JTable tblMateriali;
    private JScrollPane contentMateriali;
    private JPanel contentAggiungi;
    private JButton btnAggiungi;
    private JLabel lblIconaRicerca;

    //componenti per le operazioni sui materiali didattici
    private DefaultTableModel tableModel;
    private JPopupMenu contextMenu;
    private JMenuItem menuApri;
    private JMenuItem menuModifica;
    private JMenuItem menuRimuovi;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 1, new Insets(10, 10, 10, 10), -1, 15));
        contentRicerca = new JPanel();
        contentRicerca.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), 10, -1));
        contentPane.add(contentRicerca, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        txtRicerca = new JTextField();
        txtRicerca.setText("Inserisci parola chiave ...");
        contentRicerca.add(txtRicerca, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cmbFiltro = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("titolo");
        defaultComboBoxModel1.addElement("descrizione");
        defaultComboBoxModel1.addElement("categoria");
        cmbFiltro.setModel(defaultComboBoxModel1);
        contentRicerca.add(cmbFiltro, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRicerca = new JButton();
        Font btnRicercaFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnRicerca.getFont());
        if (btnRicercaFont != null) btnRicerca.setFont(btnRicercaFont);
        btnRicerca.setText("Ricerca");
        contentRicerca.add(btnRicerca, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIconaRicerca = new JLabel();
        lblIconaRicerca.setText("");
        contentRicerca.add(lblIconaRicerca, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        contentMateriali = new JScrollPane();
        contentPane.add(contentMateriali, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblMateriali = new JTable();
        tblMateriali.setRowHeight(25);
        contentMateriali.setViewportView(tblMateriali);
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        contentAggiungi = new JPanel();
        contentAggiungi.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentAggiungi, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnAggiungi = new JButton();
        Font btnAggiungiFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnAggiungi.getFont());
        if (btnAggiungiFont != null) btnAggiungi.setFont(btnAggiungiFont);
        btnAggiungi.setText("Aggiungi +");
        contentAggiungi.add(btnAggiungi, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


    public void apriDocenteDashboard() {
        // 1. Impostazioni base della finestra
        JFrame frame = new JFrame("Piattaforma Didattica - Dashboard Docente");
        frame.setContentPane(contentPane); // Collega il pannello principale

        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);

        inizializzaTabella();
        inizializzaMenu();

    }

    private void inizializzaMenu() {
        contextMenu = new JPopupMenu();
        menuApri = new JMenuItem("Apri File");
        menuModifica = new JMenuItem("Modifica Materiale");
        menuRimuovi = new JMenuItem("Rimuovi Materiale");

        contextMenu.add(menuApri);
        contextMenu.add(menuModifica);
        contextMenu.add(menuRimuovi);

        //collegamento per far apparire il menu
        tblMateriali.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    mostraMenu(e);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    mostraMenu(e);
                }
            }

            private void mostraMenu(MouseEvent e) {
                int rigaCliccata = tblMateriali.rowAtPoint(e.getPoint());
                if (rigaCliccata >= 0 && rigaCliccata < tblMateriali.getRowCount()) {
                    tblMateriali.setRowSelectionInterval(rigaCliccata, rigaCliccata);
                    contextMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private void inizializzaTabella() {
        // Definisci i nomi delle colonne
        String[] nomiColonne = {"Titolo", "Categoria", "Data Pubblicazione", "Sezione", "Stato"};

        // Crea il modello personalizzato bloccando la modifica delle celle
        DefaultTableModel modelloTabella = new DefaultTableModel(nomiColonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };


        // Assegna il modello alla tabella
        modelloTabella.addRow(new Object[]{"Slide Requisiti", "Slide", "28/05/2026", "Modulo 1", "pubblicato"});


        // Imposta il modello della tabella come modello della visualizzazione
        tblMateriali.setModel(modelloTabella);
    }


    //prova per visualizzare
    public static void main(String[] args) {
        DocenteDashboardMateriali dashboard = new DocenteDashboardMateriali();
        dashboard.apriDocenteDashboard();
    }


}
