package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.GestorePiattaformaSara;


import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RegistrazioneForm {
    private JPanel contentPane;
    private JLabel logo;
    private JLabel txtTitolo;
    private JLabel labelEmail;
    private JTextField txtEmail;
    private JLabel labelNome;
    private JTextField txtNome;
    private JLabel labelCognome;
    private JTextField txtCognome;
    private JLabel labelPassword;
    private JPasswordField txtPassword;
    private JRadioButton rdbStudente;
    private JRadioButton rdbDocente;
    private JButton btnRegistra;
    private JLabel labelMatricola;
    private JTextField txtMatricola;

    private JFrame frameRegistrazione;

    private GestorePiattaformaSara gestorePiattaforma;

    public RegistrazioneForm() {

        this.gestorePiattaforma = new GestorePiattaformaSara();

        btnRegistra.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eseguiRegistrazione();

            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(16, 6, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setPreferredSize(new Dimension(400, 500));
        logo = new JLabel();
        logo.setText("");
        contentPane.add(logo, new GridConstraints(0, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTitolo = new JLabel();
        txtTitolo.setText("Registrazione a StudioParadigm");
        contentPane.add(txtTitolo, new GridConstraints(1, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelEmail = new JLabel();
        labelEmail.setText("Email");
        contentPane.add(labelEmail, new GridConstraints(3, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtEmail = new JTextField();
        contentPane.add(txtEmail, new GridConstraints(4, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelNome = new JLabel();
        labelNome.setText("Nome");
        contentPane.add(labelNome, new GridConstraints(7, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNome = new JTextField();
        contentPane.add(txtNome, new GridConstraints(8, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelCognome = new JLabel();
        labelCognome.setText("Cognome");
        contentPane.add(labelCognome, new GridConstraints(9, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCognome = new JTextField();
        contentPane.add(txtCognome, new GridConstraints(10, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelPassword = new JLabel();
        labelPassword.setText("Password");
        contentPane.add(labelPassword, new GridConstraints(11, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRegistra = new JButton();
        btnRegistra.setText("Registra");
        contentPane.add(btnRegistra, new GridConstraints(14, 2, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPassword = new JPasswordField();
        contentPane.add(txtPassword, new GridConstraints(12, 2, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        rdbStudente = new JRadioButton();
        rdbStudente.setText("Studente");
        contentPane.add(rdbStudente, new GridConstraints(13, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rdbDocente = new JRadioButton();
        rdbDocente.setText("Docente");
        contentPane.add(rdbDocente, new GridConstraints(13, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        labelMatricola = new JLabel();
        labelMatricola.setText("Matricola");
        contentPane.add(labelMatricola, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtMatricola = new JTextField();
        contentPane.add(txtMatricola, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdbStudente);
        buttonGroup.add(rdbDocente);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    public JFrame apriRegistrazioneForm() {

        JFrame frame = new JFrame("Piattaforma Didattica - Registrazione alla piattaforma");

        this.frameRegistrazione = frame;

        frame.setContentPane(contentPane);

        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/logoLogin.png"));
        Image img = logoIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(img));
        logo.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 10));
        logo.setHorizontalAlignment(SwingConstants.CENTER);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 500);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;

    }

    public static void main(String[] args) {

        RegistrazioneForm frameRegistrazione = new RegistrazioneForm();

        frameRegistrazione.apriRegistrazioneForm();
    }

    private void eseguiRegistrazione() {
        String email = txtEmail.getText();
        String matricola = txtMatricola.getText();
        String nome = txtNome.getText();
        String cognome = txtCognome.getText();
        String password = new String(txtPassword.getPassword());
        boolean isStudente = rdbStudente.isSelected();
        boolean isDocente = rdbDocente.isSelected();

        if (email.isEmpty() || matricola.isEmpty() || nome.isEmpty() || cognome.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Tutti i campi di testo sono obbligatori.",
                    "Errore di inserimento",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }


        if (!isStudente && !isDocente) {
            JOptionPane.showMessageDialog(
                    null,
                    "Devi selezionare se sei Studente o Docente.",
                    "Errore di inserimento",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }


        int esito = gestorePiattaforma.inserimentoDatiUtente(email,matricola, nome, cognome, password, isStudente);

        switch (esito) {

            case GestorePiattaformaSara.REGISTRAZIONE_AVVENUTA:
                JOptionPane.showMessageDialog(
                        null,
                        "Registrazione salvata correttamente! Ora puoi effettuare l'accesso.",
                        "Esito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                LoginForm loginForm = new LoginForm();
                loginForm.apriLoginForm();

                if (frameRegistrazione != null) {
                    frameRegistrazione.dispose();
                }
                break;

            case GestorePiattaformaSara.REGISTRAZIONE_FALLITA_DOMINIO_ERRATO:
                JOptionPane.showMessageDialog(
                        null,
                        "Devi utilizzare l'email istituzionale dell'Ateneo (@unina.it).",
                        "Errore di inserimento",
                        JOptionPane.ERROR_MESSAGE
                );
                break;

            case GestorePiattaformaSara.REGISTRAZIONE_FALLITA_EMAIL_ESISTENTE:
                // [ESTENSIONE 1.1.a] - Email già utilizzata
                JOptionPane.showMessageDialog(
                        null,
                        "Attenzione: questa email è già associata a un account esistente.",
                        "Email già utilizzata",
                        JOptionPane.WARNING_MESSAGE
                );

                LoginForm loginEsistente = new LoginForm();
                loginEsistente.apriLoginForm();

                if (frameRegistrazione != null) {
                    frameRegistrazione.dispose();
                }
                break;

            case GestorePiattaformaSara.REGISTRAZIONE_FALLITA_MATRICOLA_ESISTENTE:
                JOptionPane.showMessageDialog(
                        null,
                        "Attenzione: questa matricola risulta già registrata nel sistema.",
                        "Matricola già utilizzata",
                        JOptionPane.WARNING_MESSAGE
                );
                break;

            case GestorePiattaformaSara.REGISTRAZIONE_FALLITA_MATRICOLA_ERRATA:
                String messaggioErrore;
                if (isStudente) {
                    messaggioErrore = "Formato matricola studente non valido!\nDeve iniziare con 'N4600' e contenere 9 caratteri in totale.";
                } else {
                    messaggioErrore = "Formato ID docente non valido!\nDeve iniziare con 'DOC'.";
                }

                JOptionPane.showMessageDialog(
                        null,
                        messaggioErrore,
                        "Errore di inserimento",
                        JOptionPane.ERROR_MESSAGE
                );
                break;

            default:
                JOptionPane.showMessageDialog(
                        null,
                        "Si è verificato un errore imprevisto durante la registrazione.",
                        "Errore di sistema",
                        JOptionPane.ERROR_MESSAGE
                );
                break;
        }

    }

}
