package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RegistrazioneForm {
    private JPanel contentPane;
    private JLabel logo;
    private JLabel txtTitolo;
    private JLabel labelEmail;
    private JTextField txtEmail;
    private JLabel labelNome;
    private JTextField txtNome;
    private JLabel labelCognome;
    private JTextField txtCognome;
    private JLabel labelPassword;
    private JPasswordField txtPassword;
    private JRadioButton rdbStudente;
    private JRadioButton rdbDocente;
    private JButton btnRegistra;

    private JFrame frameRegistrazione;

    public RegistrazioneForm() {
        btnRegistra.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eseguiRegistrazione();

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }



    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(14, 5, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setPreferredSize(new Dimension(400, 500));
        logo = new JLabel();
        logo.setText("");
        contentPane.add(logo, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTitolo = new JLabel();
        txtTitolo.setText("Registrazione a StudioParadigm");
        contentPane.add(txtTitolo, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelEmail = new JLabel();
        labelEmail.setText("Email");
        contentPane.add(labelEmail, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtEmail = new JTextField();
        contentPane.add(txtEmail, new GridConstraints(4, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelNome = new JLabel();
        labelNome.setText("Nome");
        contentPane.add(labelNome, new GridConstraints(5, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNome = new JTextField();
        contentPane.add(txtNome, new GridConstraints(6, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelCognome = new JLabel();
        labelCognome.setText("Cognome");
        contentPane.add(labelCognome, new GridConstraints(7, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCognome = new JTextField();
        contentPane.add(txtCognome, new GridConstraints(8, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelPassword = new JLabel();
        labelPassword.setText("Password");
        contentPane.add(labelPassword, new GridConstraints(9, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRegistra = new JButton();
        btnRegistra.setText("Registra");
        contentPane.add(btnRegistra, new GridConstraints(12, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPassword = new JPasswordField();
        contentPane.add(txtPassword, new GridConstraints(10, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        rdbStudente = new JRadioButton();
        rdbStudente.setText("Studente");
        contentPane.add(rdbStudente, new GridConstraints(11, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rdbDocente = new JRadioButton();
        rdbDocente.setText("Docente");
        contentPane.add(rdbDocente, new GridConstraints(11, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdbStudente);
        buttonGroup.add(rdbDocente);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    public JFrame apriRegistrazioneForm() {

        JFrame frame = new JFrame("Piattaforma Didattica - Registrazione alla piattaforma");

        this.frameRegistrazione=frame;

        frame.setContentPane(contentPane);

        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/logoLogin.png"));
        Image img = logoIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(img));
        logo.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 10));
        logo.setHorizontalAlignment(SwingConstants.CENTER);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 500);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;

    }

    public static void main(String[] args) {

        RegistrazioneForm frameRegistrazione = new RegistrazioneForm();

        frameRegistrazione.apriRegistrazioneForm();
    }

    private void eseguiRegistrazione() {
        String email = txtEmail.getText();
        String nome = txtNome.getText();
        String cognome = txtCognome.getText();
        String password = new String(txtPassword.getPassword());
        boolean isStudente = rdbStudente.isSelected();
        boolean isDocente = rdbDocente.isSelected();

        if (email.isEmpty() || nome.isEmpty() || cognome.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Tutti i campi di testo sono obbligatori.",
                    "Errore di inserimento",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

       /*va scelto e cambiato il dominio universitario e forse questo controllo va spostato nella classe GestoreUtente
        if (!email.endsWith("@studenti.unina.it") && !email.endsWith("@unina.it")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Devi utilizzare un'email istituzionale (@studenti.unina.it o @unina.it).",
                    "Errore di inserimento",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        */


        if (!isStudente && !isDocente) {
            JOptionPane.showMessageDialog(
                    null,
                    "Devi selezionare se sei Studente o Docente.",
                    "Errore di inserimento",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }


        String ruolo = "";
        if (isStudente) {
            ruolo = "Studente";
        } else {
            ruolo = "Docente";
        }

        //esito deve venire dal controller
        // boolean esito = RegistrazioneControllerStub.salvaUtente(email, nome, cognome, password, ruolo) una roba simile;
        boolean esito = true;


        if (esito) {
            JOptionPane.showMessageDialog(
                    null,
                    "Registrazione salvata correttamente",
                    "Esito",
                    JOptionPane.INFORMATION_MESSAGE
            );


            if (frameRegistrazione != null) {
                frameRegistrazione.dispose();
            }

        } else {
            // [ESTENSIONE 1.1.a] - Email già utilizzata
            // 1. Notifica l'utente riguardo la precedente registrazione
            JOptionPane.showMessageDialog(
                    null,
                    "Attenzione: questa email è già associata a un account esistente.",
                    "Email già utilizzata",
                    JOptionPane.WARNING_MESSAGE
            );

            // 2. Il sistema reindirizza l'utente alla schermata di accesso
            LoginForm login = new LoginForm();
            login.apriLoginForm();

            if (frameRegistrazione != null) {
                frameRegistrazione.dispose();
            }
        }
    }

}
