package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.*;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.util.List;
import java.util.Locale;


public class StudenteDashboardMateriali {


    private JPanel contentPane;
    private JPanel contentRicerca;
    private JComboBox cmbFiltro;
    private JButton btnRicerca;
    private JTextField txtRicerca;
    private JScrollPane contentMateriali;
    private JTable tblMateriali;
    private JPanel contentDescrizione;
    private JLabel lblMateriali;
    private JLabel lblCorso;
    private JPanel descrizioneDashboard;
    private JLabel iconaLogo;
    private JLabel lblStudente;
    private JLabel lbl_informazioniStudenti;
    private JButton btnIndietro;

    private JFrame frameAggiungi;
    private JFrame myFrame;
    private JFrame frameLogin;

    //componenti per le operazioni sui materiali didattici
    private DefaultTableModel tableModel;
    private JPopupMenu contextMenu;
    private JMenuItem menuApri;

    //dati dello studente
    private String emailUtente;
    private String nomeCorso;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, -1));
        contentRicerca = new JPanel();
        contentRicerca.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), 10, -1));
        contentPane.add(contentRicerca, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        cmbFiltro = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("titolo");
        defaultComboBoxModel1.addElement("descrizione");
        defaultComboBoxModel1.addElement("categoria");
        cmbFiltro.setModel(defaultComboBoxModel1);
        contentRicerca.add(cmbFiltro, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRicerca = new JButton();
        Font btnRicercaFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnRicerca.getFont());
        if (btnRicercaFont != null) btnRicerca.setFont(btnRicercaFont);
        btnRicerca.setText("Ricerca");
        contentRicerca.add(btnRicerca, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtRicerca = new JTextField();
        txtRicerca.setText("Inserisci parola chiave ...");
        contentRicerca.add(txtRicerca, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        contentMateriali = new JScrollPane();
        contentPane.add(contentMateriali, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblMateriali = new JTable();
        tblMateriali.setRowHeight(25);
        contentMateriali.setViewportView(tblMateriali);
        contentDescrizione = new JPanel();
        contentDescrizione.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentDescrizione, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblMateriali = new JLabel();
        Font lblMaterialiFont = this.$$$getFont$$$(null, Font.BOLD, 16, lblMateriali.getFont());
        if (lblMaterialiFont != null) lblMateriali.setFont(lblMaterialiFont);
        lblMateriali.setText("Materiali Didattici Corso");
        contentDescrizione.add(lblMateriali, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCorso = new JLabel();
        Font lblCorsoFont = this.$$$getFont$$$(null, Font.BOLD, 16, lblCorso.getFont());
        if (lblCorsoFont != null) lblCorso.setFont(lblCorsoFont);
        lblCorso.setText("\"nome_corso\"");
        contentDescrizione.add(lblCorso, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentDescrizione.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        descrizioneDashboard = new JPanel();
        descrizioneDashboard.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(descrizioneDashboard, new GridConstraints(0, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        iconaLogo = new JLabel();
        iconaLogo.setText("");
        descrizioneDashboard.add(iconaLogo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblStudente = new JLabel();
        lblStudente.setText("Studente");
        descrizioneDashboard.add(lblStudente, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnIndietro = new JButton();
        Font btnIndietroFont = this.$$$getFont$$$(null, Font.BOLD, 14, btnIndietro.getFont());
        if (btnIndietroFont != null) btnIndietro.setFont(btnIndietroFont);
        btnIndietro.setMargin(new Insets(10, 10, 10, 10));
        btnIndietro.setText("Indietro");
        descrizioneDashboard.add(btnIndietro, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbl_informazioniStudenti = new JLabel();
        lbl_informazioniStudenti.setText("\"nome studente\"");
        descrizioneDashboard.add(lbl_informazioniStudenti, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        descrizioneDashboard.add(spacer3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        contentPane.add(spacer4, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    //Aggiungere nel costruttore l'email dell'utente e il corso
    public StudenteDashboardMateriali(String emailUtente, String nomeCorso) {
        this.emailUtente = emailUtente;
        this.nomeCorso = nomeCorso;
        inizializzaTabella();
        inizializzaMenu();
        setAzioni();
        aggiornaTabellaMateriali();
        lblCorso.setText(nomeCorso);
        lbl_informazioniStudenti.setText(emailUtente);

        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/logoPiattaforma.png"));
        Image img = logoIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        iconaLogo.setIcon(new ImageIcon(img));
        iconaLogo.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        iconaLogo.setHorizontalAlignment(SwingConstants.CENTER);

    }

    public JFrame apriStudenteDashboard() {
        // 1. Impostazioni base della finestra
        JFrame frame = new JFrame("Studio Paradigm - Dashboard Studente");
        this.myFrame = frame;
        frame.setContentPane(contentPane); // Collega il pannello principale
        txtRicerca.setForeground(Color.GRAY);


        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                frame.dispose(); // Libera l'istanza statica
            }
        });
        return frame;
    }

    private void inizializzaMenu() {
        contextMenu = new JPopupMenu();
        menuApri = new JMenuItem("Apri File");

        contextMenu.add(menuApri);

        //collegamento per far apparire il menu
        tblMateriali.addMouseListener(new MouseAdapter() {

            // tasto destro
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger())
                    mouseClicked(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger())
                    mouseClicked(e);
            }

            // click sinistro sulla colonna ⋮
            @Override
            public void mouseClicked(MouseEvent e) {
                int col = tblMateriali.columnAtPoint(e.getPoint());
                int row = tblMateriali.rowAtPoint(e.getPoint());
                if (col == 5 && row >= 0 && row < tblMateriali.getRowCount()) {
                    tblMateriali.setRowSelectionInterval(row, row);
                    contextMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }

        });
    }

    private void inizializzaTabella() {
        // Definisci i nomi delle colonne
        String[] nomiColonne = {"Titolo", "Categoria", "Descrizione", "Data Pubblicazione", "Sezione","Azioni"};

        // Crea il modello personalizzato bloccando la modifica delle celle
        tableModel = new DefaultTableModel(nomiColonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Imposta il modello della tabella come modello della visualizzazione
        tblMateriali.setModel(tableModel);

        // Centra il contenuto dell'ultima colonna (indice 5)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblMateriali.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tblMateriali.getColumnModel().getColumn(5).setPreferredWidth(50);
    }

    //metodo per popolare la tabella
    public void aggiornaTabellaMateriali() {
        // Richiama il tuo metodo per ottenere i dati
        List<String[]> datiMateriali = GestorePiattaforma.visualizzaMaterialiPubblicati(this.nomeCorso);

        //Ottieni il modello della tua JTable
        tableModel = (DefaultTableModel) tblMateriali.getModel();

        // Pulire la tabella dai dati vecchi
        tableModel.setRowCount(0);

        //Cicla la lista e aggiunge ogni array come riga al modello
        for (String[] riga : datiMateriali) {
            tableModel.addRow(riga);
        }
    }

    private void setAzioni() {
        //Azione click Apri
        menuApri.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int rigaSelezionata = tblMateriali.getSelectedRow();

                // Prima controlliamo che una riga sia effettivamente selezionata!
                if (rigaSelezionata != -1) {
                    String titoloSelezionato = tblMateriali.getValueAt(rigaSelezionata, 0).toString();
                    boolean esito = GestorePiattaforma.apriMateriale(nomeCorso, titoloSelezionato);

                    if (esito) {
                        JOptionPane.showMessageDialog(contentPane, "File aperto con successo.", "Operazione completata", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(contentPane, "Errore: impossibile aprire il file. Verifica che esista sul disco.", "Errore", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });


        //Azione click test ricerca FATTA
        txtRicerca.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtRicerca.getText().equals("Inserisci parola chiave ...")) {
                    txtRicerca.setText("");
                    txtRicerca.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtRicerca.getText().isBlank()) {
                    txtRicerca.setText("Inserisci parola chiave ...");
                    txtRicerca.setForeground(Color.GRAY);
                }
            }
        });

        //Azione click ricerca
        btnRicerca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<String[]> datiMateriali = GestorePiattaforma.visualizzaMaterialiPubblicati(nomeCorso,
                        (Object) txtRicerca.getText(),
                        (String) cmbFiltro.getSelectedItem());

                //Ottieni il modello della tua JTable
                tableModel = (DefaultTableModel) tblMateriali.getModel();

                // Pulire la tabella dai dati vecchi
                tableModel.setRowCount(0);

                //Cicla la lista e aggiunge ogni array come riga al modello
                for (String[] riga : datiMateriali) {
                    tableModel.addRow(riga);
                }
            }
        });

        btnIndietro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (myFrame != null) {
                    myFrame.dispose();
                    AreaRiservataStudente form = new AreaRiservataStudente(emailUtente);
                    myFrame = form.apriAreaRiservataStudente();
                }

            }
        });

    }

}

